[package]
name = "man_down"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
reqwest = { version = "0.11.4", features = ["blocking", "json"] }
tokio = { version = "1.8.3", features = ["full"] }
serde = "1.0.130"
serde_derive = "1.0.130"
futures = "0.3.28"
dotenv = "0.15.0"
teloxide = { version = "0.12", features = ["auto-send", "macros"] }
