name: Poller Build and Push

on:
  push:
    branches:
      - main
    paths:
      - '.containerignore'
      - '.github/actions/podman-build/**'
      - '.github/workflows/poller-build-push.yaml'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'config.yaml'
      - 'crates/core/**'
      - 'crates/poller/**'

env:
  GH_TOKEN: ${{ secrets.MANDOWN_PAT }}

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build and Push Poller
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build and push poller container
        uses: ./.github/actions/podman-build
        with:
          containerfile: crates/poller/Containerfile
          image_name: mandown-poller
          push: 'true'
          github_variable: IMAGE_POLLER
