name: Webhook Build and Push

on:
  push:
    branches:
      - main
    paths:
      - '.containerignore'
      - '.github/actions/podman-build/**'
      - '.github/workflows/webhook-build-push.yaml'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'config.yaml'
      - 'crates/core/**'
      - 'crates/webhook/**'

env:
  GH_TOKEN: ${{ secrets.MANDOWN_PAT }}

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build and Push Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Build and push webhook container
        uses: ./.github/actions/podman-build
        with:
          containerfile: crates/webhook/Containerfile
          image_name: mandown-webhook
          push: 'true'
          github_variable: IMAGE_WEBHOOK
