name: Webhook Build and Push

on:
  push:
    branches:
      - main
      - repocleanup
    paths:
      - '.containerignore'
      - '.github/actions/container-build/**'
      - '.github/workflows/webhook-build-push.yaml'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'config.yaml'
      - 'crates/core/**'
      - 'crates/webhook/**'

env:
  GH_TOKEN: ${{ secrets.MANDOWN_PAT }}

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build and Push Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build and push webhook container
        uses: ./.github/actions/container-build
        with:
          containerfile: crates/webhook/Containerfile
          image_name: mandown-webhook
          push: 'true'
          github_variable: IMAGE_WEBHOOK
          repository_uri: ${{ vars.REPOSITORY_URI }}
          registry_uri: ${{ vars.REGISTRY_URI }}
          gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
          gcp_wif: ${{ vars.GCP_WIF }}
